spring.application.name=p18-backend

# Disable DB temporarily
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Server Port (VERY IMPORTANT)
server.port=${PORT:8080}